from typing import Protocol

from domain.subdomain.entities.user import User


class UserRepositoryInterface(Protocol):
  def create(self, user: User) -> User: ...
  def get(self, ulid: str) -> User: ...
  def get_by_username(self, username: str) -> User: ...
  def update(self, user: User) -> User: ...
  def delete(self, ulid: str) -> User: ...
